server:
  #服务提供者端口号
  port: 40001
spring:
  application:
    name: ServerProvide
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:30001/eureka/